# version format
version: 1.2.{build}

branches:
  only:
  - master

configuration: Release

platform: x64

# Install scripts
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node 5.0.0 x64

  - npm -v
  - node -v
  # get a node binary for distribution
  - curl -LsSO https://nodejs.org/dist/latest/win-x64/node.exe
  - curl -LsSO https://nodejs.org/dist/latest/win-x64/node.lib
  # - npm install npm
  - npm install --production --msvs_version=2013
  - npm install -g kthxbai
  - kthxbai
  - copy bin\sabi.bat sabi.bat
  - 7z a -tzip sabi-%APPVEYOR_BUILD_VERSION%.zip sabi.bat node.exe ace.html form.html AUTHORS ChangeLog config images lib src node_modules package.json server.js scripts LICENSE OWNERS README.md users.htpasswd
  - dir

# Post-install test scripts.
# test_script:
# cmd: C:\Qt\5.4\msvc2013_64_opengl\bin\binarycreator
# cmd: C:\Qt\QtIFW2.0.1\bin\binarycreator

# Don't actually build.
build: off

artifacts:
  - path: sabi-$(APPVEYOR_BUILD_VERSION).zip
    name: sabi

deploy:
  provider: FTP
  protocol: ftp
  host: ftp.evl.uic.edu
  username: anonymous
  password: luc@evl
  folder: /pub/INcoming/luc/app/
  artifact: sabi

# cache:
#   - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
#   - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
#   - node_modules -> package.json                                        # local npm modules
